owner: divideprojects
repo: uptime-monitor

sites:
  - name: DivideProjects.com
    url: https://divideprojects.com
  - name: API: hCaptcha Verifier
    url: https://hcaptcha-verifier.divideprojects.com/alive
  - name: API: ping-back
    url: https://ping-back.divideprojects.com/alive
  - name: Oracle Server
    url: $ORACLE_SERVER
  - name: TG Bot: Public Link 🔗 Robot
    url: https://publiclink-bot.divideprojects.com
  - name: TG Bot: Alita_Robot
    url: https://alita-robot.divideprojects.com
    headers:
      - "CF-Access-Client-Id: $CF_ACCESS_ID"
      - "CF-Access-Client-Secret: $CF_ACCESS_SECRET"

status-website:
  cname: status.divideprojects.com
  logoUrl: https://raw.githubusercontent.com/DivideProjects/.github/main/DivideProjects.png
  name: Status Monitor
  navbar:
    - title: Telegram
      href: https://t.me/$OWNER
    - title: GitHub
      href: https://github.com/$OWNER

workflowSchedule:
  graphs: "3 */3 * * *"
  responseTime: "0 */3 * * *"
  staticSite: "0 1 * * *"
  summary: "5 */3 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
