# Change these first
owner: divideprojects # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: DivideProjects Website
    url: https://divideprojects.com
  - name: FileStreamBot
    url: https://publiclink-bot.divideprojects.com
  - name: Go-Paste API
    url: https://go-paste.svc.divideprojects.com/alive
  - name: hCaptcha Verifier API
    url: https://hcaptcha-verifier.divideprojects.com/alive
  - name: ping-back API
    url: https://ping-back.divideprojects.com/alive

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.divideprojects.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
