owner: divideprojects
repo: uptime-monitor

sites:
  - name: DivideProjects Website
    url: https://divideprojects.com
  - name: FileStreamBot
    url: https://publiclink-bot.divideprojects.com
  - name: Go-Paste API
    url: https://go-paste.svc.divideprojects.com/alive
  - name: hCaptcha Verifier API
    url: https://hcaptcha-verifier.divideprojects.com/alive
  - name: ping-back API
    url: https://ping-back.divideprojects.com/alive
  - name: Oracle Server
    url: $ORACLE_SERVER

status-website:
  cname: status.divideprojects.com
  logoUrl: https://raw.githubusercontent.com/DivideProjects/.github/main/DivideProjects.png
  name: Uptime Monitor
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  theme: dark
  navbar:
    - title: Telegram
      href: https://t.me/$OWNER


workflowSchedule:
  graphs: "3 */1 * * *"
  responseTime: "0 */1 * * *"
  staticSite: "0 1 * * *"
  summary: "5 */1 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"
